development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://chatfayeserver.herokuapp.com/faye"
  secret_token: "kevinrocjs"
  signature_expiration: 86400 # one hour
   # 86400 # one day


